// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwuryrwxxyuyvbrwhjdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3dXJ5cnd4eHl1eXZicndoamRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4OTQwMDksImV4cCI6MjA3NjQ3MDAwOX0.H9RrvMvOodkJkXhrwRHgOcugQzxzrk1iUgs8vAAAHAY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});